name: BlueMapChatMarkers
version: '${version}'
main: com.technicjelle.bluemapchatmarkers.BlueMapChatMarkers
api-version: 1.13
depend: [ BlueMap ]
authors: [ TechnicJelle ]
description: Adds chat messages to BlueMap
website: https://github.com/TechnicJelle/BlueMapChatMarkers
