name: BlueMapVentureChatMarkers
version: '${version}'
main: com.technicjelle.bluemapchatmarkers.BlueMapChatMarkers
api-version: 1.13
depend: [ BlueMap, VentureChat ]
authors: [ TechnicJelle, Mark_225 ]
description: Adds VentureChat messages to BlueMap. Fork of BlueMapChatMarkers.
website: https://github.com/Mark-225/BlueMapVentureChatMarkers
